name: 'Build with Apache Maven'

description: Build with Apache Maven

inputs:
  github-repository:
    description: 'GitHub repository in the format owner/repo ; ex: github.repository variable'
    required: true
  github-token:
    description: 'Password or token for server authentication ; ex: secrets.GITHUB_TOKEN variable'
    required: true

runs:

  using: 'composite'

  steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - run: mvn clean site
      shell: bash

    - name: Publish site to gh-pages branch
      run: |
        gh repo clone ${{ inputs.github-repository }} repo-tmp
        cd repo-tmp
        git checkout gh-pages || git checkout --orphan gh-pages
        rm -rf *
        cp -r ../target/site/* .
        git add .
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ inputs.github-repository }}.git
        git commit -m "Deploy Maven site"
        git push origin gh-pages --force
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash